### ISSUE TITLE
distance between the food particles

### ISSUE THREAD

**Issue by dhairyaj** [Project-DC/chimichangas#6]

**Comment by frankhart2018** [comment]
How about you loop through all of the food particles after they are created and then delete the ones which overlap, you can check that using euclidean distance. Since not many particles will overlap I believe this is the simplest solution.

**Comment by frankhart2018** [comment]
> @dhairyaj How about you loop through all of the food particles after they are created and then delete the ones which overlap, you can check that using euclidean distance. Since not many particles will overlap I believe this is the simplest solution.@dhairyaj How about you loop through all of the food particles after they are created and then delete the ones which overlap, you can check that using euclidean distance. Since not many particles will overlap I believe this is the simplest solution.
<sub>[View in Slack](https://projectdcworkspace.slack.com/archives/C015GBRRC15/p1592933400002800)</sub>

**Comment by frankhart2018** [comment]
Merged
